version: '3'

networks:
  proxy:
    driver: bridge
  frontend:
    driver: bridge
    internal: true
  backend:
    driver: bridge
    internal: true

services:
  proxy:
    image: ghcr.io/shinerising/crop-reverse-proxy:master
    restart: always
    volumes:
      - /volume1/docker/crop/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3380:80"
      - "33443:443"
    environment:
      - URL_DARS=dars:8376
    networks:
      - proxy
      - frontend

  dars:
    image: ghcr.io/shinerising/station-stats:master
    restart: always
    volumes:
      - /volume1/docker/station-stats/config:/config:ro
      - /volume1/docker/station-stats/station:/station:ro
      - /volume1/docker/station-stats/data:/data:ro
    ports:
      - "8376:8376"
    environment:
      - SERVER_CONFIG=/config/server.xml
      - STATION_CONFIG=/config/station.xml
    networks:
      - frontend