version: '3'

networks:
  proxy:
    driver: bridge
  frontend:
    driver: bridge
    internal: true
  backend:
    driver: bridge
    internal: true

volumes:
  asset-dars:
  asset-dashboard:

services:
  proxy:
    image: ghcr.io/shinerising/crop-reverse-proxy:master
    restart: always
    volumes:
      - asset-dars:/usr/share/nginx/asset-dars:ro
      - asset-dashboard:/usr/share/nginx/asset-dashboard:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      - URL_DARS=dars:8376
      - URL_DASHBOARD=dashboard:7344
    networks:
      - proxy
      - frontend

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=crop
      - POSTGRES_PASSWORD=crop
      - POSTGRES_DB=db_crop
    volumes:
      - /etc/docker/volume/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
  
  redis:
    image: redis/redis-stack-server:7.2.0-v5
    volumes:
      - /etc/docker/volume/redis-stack:/data
    ports:
      - "6379:6379"
    networks:
      - backend

  dars:
    image: ghcr.io/shinerising/station-stats:master
    restart: always
    volumes:
      - asset-dars:/App/public
      - /etc/docker/volume/station-stats/config:/config
      - /etc/docker/volume/station-stats/station:/station
      - /etc/docker/volume/station-stats/data:/data
    ports:
      - "8376:8376"
    environment:
      - SERVER_CONFIG=/config/server.xml
      - STATION_CONFIG=/config/station.xml
    networks:
      - frontend

  dashboard:
    image: ghcr.io/shinerising/crop-dashboard:main
    restart: always
    volumes:
      - asset-dashboard:/App/public
    ports:
      - "7344:80"
    tty: true
    networks:
      - frontend